SM:
  - 0.99355742615604381
  - 0.019183174615620868
  - 0.0037110444042498252
  - -0.0093062159685169486
  - 0.99609179261077796
  - -0.0068829537207338492
  - -0.024634142095995525
  - -0.027486237999159946
  - 0.98819094000921892
bias:
  - 0.088221215188824489
  - -0.24368396063849299
  - -0.42420965563770352
