SM:
  - 0.99996420794496976
  - -0.0052987116996434883
  - -0.013801640341339431
  - -0.0025649884918210256
  - 1.0051825942918895
  - 0.0100412459925987
  - -0.018802214662067843
  - 0.0071081045148608689
  - 0.98857696456458399
bias:
  - -0.19384192241689813
  - 0.15877528034891808
  - 2.2302329203727527